export { Home } from "./Home";
export { FullPost } from "./FullPost";
export { AddPost } from "./AddPost";
export { Registration } from "./Registration";
export { Login } from "./Login";
export { Error } from "./404";
export { Wheel } from "./Wheel";
export { Test } from "./test";
export { Me } from "./Me";